In [1]:
import pandas as pd

In [2]:
def load_data():
    sales_df = pd.read_csv("sales_data.csv")
    products_df = pd.read_csv("products.csv")
    stores_df = pd.read_csv("stores.csv")

    return sales_df, products_df, stores_df

In [3]:
sales_df, products_df, stores_df = load_data()

In [4]:
sales_df

   sale_id store_id product_id quantity   sale_date  amount
0     S001     ST01       P001        5  2026-06-01  2500.0
1     S002     ST02       P003        2  2026-06-01   900.0
2     S003     ST03       P002      NaN  2026-06-01  1200.0
3     S004     ST01       P004        3  2026-06-02     NaN
4     S005     ST04       P005        1  2026-06-02  1500.0
5     S006     ST02       P006        4  2026-06-02  2000.0
6     S007     ST05       P007        2  2026-06-03   800.0
7     S008     ST03       P008      ten  2026-06-03  3000.0
8     S009     ST01       P009        6  2026-06-03  1800.0
9     S010     ST04       P010        3  2026-06-04  2100.0
10    S011     ST05       P001        2  2026-06-04  1000.0
11    S012     ST02       P002        1  2026-06-04   600.0
12    S013     ST03       P003      NaN  2026-06-05     NaN
13    S014     ST06       P004        5  2026-06-05  2500.0
14    S015     ST01       P011        2  2026-06-05   999.0
15    S016     ST04       P006        4  wrong_date  2000.0
16    S017     ST05       P007        3  2026-06-06  1200.0
17    S018     ST02       P008        2  2026-06-06  3000.0
18    S006     ST02       P006        4  2026-06-02  2000.0
19    S010     ST04       P010        3  2026-06-04  2100.0

In [5]:
products_df

   product_id    product_name     category  price
0        P001          Laptop  Electronics  50000
1        P002  Wireless Mouse  Electronics    600
2        P003        Keyboard  Electronics    450
3        P004      Headphones  Electronics    500
4        P005    Office Chair    Furniture   1500
5        P006     Study Table    Furniture    500
6        P007        Notebook   Stationery    400
7        P008         Printer  Electronics   1500
8        P009    Water Bottle         Home    300
9        P010        Backpack         Bags    700
10       P012       Desk Lamp         Home    900
11       P013         Pen Set   Stationery    150
12       P014       USB Cable  Electronics    250
13       P015         Monitor  Electronics   8000
14       P016      Calculator   Stationery    350

In [6]:
stores_df

   store_id                   store_name        city   region
0      ST01    RetailMart Jaipur Central      Jaipur    North
1      ST02         RetailMart Delhi Hub       Delhi    North
2      ST03       RetailMart Mumbai West      Mumbai     West
3      ST04    RetailMart Bangalore Tech   Bangalore    South
4      ST05      RetailMart Kolkata East     Kolkata     East
5      ST06         RetailMart Pune City        Pune     West
6      ST07     RetailMart Chennai South     Chennai    South
7      ST08   RetailMart Hyderabad Metro   Hyderabad    South
8      ST09     RetailMart Lucknow Plaza     Lucknow    North
9      ST10    RetailMart Ahmedabad Mall   Ahmedabad     West
10     ST11     RetailMart Indore Market      Indore  Central
11     ST12  RetailMart Chandigarh Point  Chandigarh    North
12     ST13     RetailMart Bhopal Center      Bhopal  Central
13     ST14       RetailMart Kochi Store       Kochi    South
14     ST15      RetailMart Surat Outlet       Surat     West

In [7]:
print("Shape:", sales_df.shape)
print(sales_df.head())

print("Shape:", products_df.shape)
print(products_df.head())

print("Shape:", stores_df.shape)
print(stores_df.head())

Shape: (20, 6)
  sale_id store_id product_id quantity   sale_date  amount
0    S001     ST01       P001        5  2026-06-01  2500.0
1    S002     ST02       P003        2  2026-06-01   900.0
2    S003     ST03       P002      NaN  2026-06-01  1200.0
3    S004     ST01       P004        3  2026-06-02     NaN
4    S005     ST04       P005        1  2026-06-02  1500.0
Shape: (15, 4)
  product_id    product_name     category  price
0       P001          Laptop  Electronics  50000
1       P002  Wireless Mouse  Electronics    600
2       P003        Keyboard  Electronics    450
3       P004      Headphones  Electronics    500
4       P005    Office Chair    Furniture   1500
Shape: (15, 4)
  store_id                 store_name       city region
0     ST01  RetailMart Jaipur Central     Jaipur  North
1     ST02       RetailMart Delhi Hub      Delhi  North
2     ST03     RetailMart Mumbai West     Mumbai   West
3     ST04  RetailMart Bangalore Tech  Bangalore  South
4     ST05    RetailMart Kolkata East    Kolkata   East

In [8]:
print("Total Null Values:")
print("Values:", sales_df.isna().sum().sum())
print("Values:", products_df.isna().sum().sum())
print("Values:", stores_df.isna().sum().sum())

Total Null Values:
Values: 4
Values: 0
Values: 0

In [9]:
print("Column Names Having Null values:")
print(list(sales_df.columns[sales_df.isnull().any()]))
print(list(products_df.columns[products_df.isnull().any()]))
print(list(stores_df.columns[stores_df.isnull().any()]))

Column Names Having Null values:
['quantity', 'amount']
[]
[]

In [10]:
sales_df = pd.read_csv("sales_data.csv")
duplicate_count = sales_df.duplicated().sum()

print("Number of duplicate rows found:", duplicate_count)
sales_df = sales_df.drop_duplicates()

print("Number of duplicate rows removed:", duplicate_count)
print("Total rows after removing duplicates:", len(sales_df))

Number of duplicate rows found: 2
Number of duplicate rows removed: 2
Total rows after removing duplicates: 18

In [11]:
sales_df['quantity'] = sales_df['quantity'].fillna(0)
sales_df = sales_df.dropna(subset=['amount'])
print("Cleaned DataFrame Shape:", sales_df.shape)

Cleaned DataFrame Shape: (16, 6)

In [12]:
sales_df['sale_date'] = pd.to_datetime(
    sales_df['sale_date'],
    errors='coerce'
)

sales_df['amount'] = pd.to_numeric(
    sales_df['amount'],
    errors='coerce'
)

sales_df['amount'] = sales_df['amount'].astype(float)

print(sales_df.dtypes)

sale_id               object
store_id              object
product_id            object
quantity              object
sale_date     datetime64[ns]
amount               float64
dtype: object

In [13]:
final_df = sales_df.merge(products_df, on='product_id', how='left') \
                   .merge(stores_df, on='store_id', how='left')

print(final_df)

   sale_id store_id product_id quantity  sale_date  amount    product_name  \
0     S001     ST01       P001        5 2026-06-01  2500.0          Laptop
1     S002     ST02       P003        2 2026-06-01   900.0        Keyboard
2     S003     ST03       P002        0 2026-06-01  1200.0  Wireless Mouse
3     S005     ST04       P005        1 2026-06-02  1500.0    Office Chair
4     S006     ST02       P006        4 2026-06-02  2000.0     Study Table
5     S007     ST05       P007        2 2026-06-03   800.0        Notebook
6     S008     ST03       P008      ten 2026-06-03  3000.0         Printer
7     S009     ST01       P009        6 2026-06-03  1800.0    Water Bottle
8     S010     ST04       P010        3 2026-06-04  2100.0        Backpack
9     S011     ST05       P001        2 2026-06-04  1000.0          Laptop
10    S012     ST02       P002        1 2026-06-04   600.0  Wireless Mouse
11    S014     ST06       P004        5 2026-06-05  2500.0      Headphones
12    S015     ST01       P011        2 2026-06-05   999.0             NaN
13    S016     ST04       P006        4        NaT  2000.0     Study Table
14    S017     ST05       P007        3 2026-06-06  1200.0        Notebook
15    S018     ST02       P008        2 2026-06-06  3000.0         Printer

       category    price                 store_name       city region
0   Electronics  50000.0  RetailMart Jaipur Central     Jaipur  North
1   Electronics    450.0       RetailMart Delhi Hub      Delhi  North
2   Electronics    600.0     RetailMart Mumbai West     Mumbai   West
3     Furniture   1500.0  RetailMart Bangalore Tech  Bangalore  South
4     Furniture    500.0       RetailMart Delhi Hub      Delhi  North
5    Stationery    400.0    RetailMart Kolkata East    Kolkata   East
6   Electronics   1500.0     RetailMart Mumbai West     Mumbai   West
7          Home    300.0  RetailMart Jaipur Central     Jaipur  North
8          Bags    700.0  RetailMart Bangalore Tech  Bangalore  South
9   Electronics  50000.0    RetailMart Kolkata East    Kolkata   East
10  Electronics    600.0       RetailMart Delhi Hub      Delhi  North
11  Electronics    500.0       RetailMart Pune City       Pune   West
12          NaN      NaN  RetailMart Jaipur Central     Jaipur  North
13    Furniture    500.0  RetailMart Bangalore Tech  Bangalore  South
14   Stationery    400.0    RetailMart Kolkata East    Kolkata   East
15  Electronics   1500.0       RetailMart Delhi Hub      Delhi  North

In [14]:
final_df['quantity'] = pd.to_numeric(final_df['quantity'],
                                     errors='coerce')

In [15]:
final_df['quantity'] = final_df['quantity'].fillna(0)

In [16]:
import numpy as np

final_df['total_revenue'] = (
    final_df['quantity'] * final_df['price']
)

print("Mean Revenue:", np.mean(final_df['total_revenue']))
print("Maximum Revenue:", np.max(final_df['total_revenue']))
print("Minimum Revenue:", np.min(final_df['total_revenue']))

Mean Revenue: 24560.0
Maximum Revenue: 250000.0
Minimum Revenue: 0.0

In [17]:
city_revenue = final_df.groupby('city')['total_revenue'].sum()
city_revenue = city_revenue.sort_values(ascending=False)
print(city_revenue)

city
Jaipur       251800.0
Kolkata      102000.0
Delhi          6500.0
Bangalore      5600.0
Pune           2500.0
Mumbai            0.0
Name: total_revenue, dtype: float64

In [18]:
print(final_df)

   sale_id store_id product_id  quantity  sale_date  amount    product_name  \
0     S001     ST01       P001       5.0 2026-06-01  2500.0          Laptop
1     S002     ST02       P003       2.0 2026-06-01   900.0        Keyboard
2     S003     ST03       P002       0.0 2026-06-01  1200.0  Wireless Mouse
3     S005     ST04       P005       1.0 2026-06-02  1500.0    Office Chair
4     S006     ST02       P006       4.0 2026-06-02  2000.0     Study Table
5     S007     ST05       P007       2.0 2026-06-03   800.0        Notebook
6     S008     ST03       P008       0.0 2026-06-03  3000.0         Printer
7     S009     ST01       P009       6.0 2026-06-03  1800.0    Water Bottle
8     S010     ST04       P010       3.0 2026-06-04  2100.0        Backpack
9     S011     ST05       P001       2.0 2026-06-04  1000.0          Laptop
10    S012     ST02       P002       1.0 2026-06-04   600.0  Wireless Mouse
11    S014     ST06       P004       5.0 2026-06-05  2500.0      Headphones
12    S015     ST01       P011       2.0 2026-06-05   999.0             NaN
13    S016     ST04       P006       4.0        NaT  2000.0     Study Table
14    S017     ST05       P007       3.0 2026-06-06  1200.0        Notebook
15    S018     ST02       P008       2.0 2026-06-06  3000.0         Printer

       category    price                 store_name       city region  \
0   Electronics  50000.0  RetailMart Jaipur Central     Jaipur  North
1   Electronics    450.0       RetailMart Delhi Hub      Delhi  North
2   Electronics    600.0     RetailMart Mumbai West     Mumbai   West
3     Furniture   1500.0  RetailMart Bangalore Tech  Bangalore  South
4     Furniture    500.0       RetailMart Delhi Hub      Delhi  North
5    Stationery    400.0    RetailMart Kolkata East    Kolkata   East
6   Electronics   1500.0     RetailMart Mumbai West     Mumbai   West
7          Home    300.0  RetailMart Jaipur Central     Jaipur  North
8          Bags    700.0  RetailMart Bangalore Tech  Bangalore  South
9   Electronics  50000.0    RetailMart Kolkata East    Kolkata   East
10  Electronics    600.0       RetailMart Delhi Hub      Delhi  North
11  Electronics    500.0       RetailMart Pune City       Pune   West
12          NaN      NaN  RetailMart Jaipur Central     Jaipur  North
13    Furniture    500.0  RetailMart Bangalore Tech  Bangalore  South
14   Stationery    400.0    RetailMart Kolkata East    Kolkata   East
15  Electronics   1500.0       RetailMart Delhi Hub      Delhi  North

    total_revenue
0        250000.0
1           900.0
2             0.0
3          1500.0
4          2000.0
5           800.0
6             0.0
7          1800.0
8          2100.0
9        100000.0
10          600.0
11         2500.0
12            NaN
13         2000.0
14         1200.0
15         3000.0

In [19]:
final_df['price'] = final_df['price'].fillna(0)
final_df['product_name'] = final_df['product_name'].fillna('Unknown')
final_df['category'] = final_df['category'].fillna('Unknown')
final_df['total_revenue']=final_df['total_revenue'].fillna(0)

In [20]:
print(final_df)

   sale_id store_id product_id  quantity  sale_date  amount    product_name  \
0     S001     ST01       P001       5.0 2026-06-01  2500.0          Laptop
1     S002     ST02       P003       2.0 2026-06-01   900.0        Keyboard
2     S003     ST03       P002       0.0 2026-06-01  1200.0  Wireless Mouse
3     S005     ST04       P005       1.0 2026-06-02  1500.0    Office Chair
4     S006     ST02       P006       4.0 2026-06-02  2000.0     Study Table
5     S007     ST05       P007       2.0 2026-06-03   800.0        Notebook
6     S008     ST03       P008       0.0 2026-06-03  3000.0         Printer
7     S009     ST01       P009       6.0 2026-06-03  1800.0    Water Bottle
8     S010     ST04       P010       3.0 2026-06-04  2100.0        Backpack
9     S011     ST05       P001       2.0 2026-06-04  1000.0          Laptop
10    S012     ST02       P002       1.0 2026-06-04   600.0  Wireless Mouse
11    S014     ST06       P004       5.0 2026-06-05  2500.0      Headphones
12    S015     ST01       P011       2.0 2026-06-05   999.0         Unknown
13    S016     ST04       P006       4.0        NaT  2000.0     Study Table
14    S017     ST05       P007       3.0 2026-06-06  1200.0        Notebook
15    S018     ST02       P008       2.0 2026-06-06  3000.0         Printer

       category    price                 store_name       city region  \
0   Electronics  50000.0  RetailMart Jaipur Central     Jaipur  North
1   Electronics    450.0       RetailMart Delhi Hub      Delhi  North
2   Electronics    600.0     RetailMart Mumbai West     Mumbai   West
3     Furniture   1500.0  RetailMart Bangalore Tech  Bangalore  South
4     Furniture    500.0       RetailMart Delhi Hub      Delhi  North
5    Stationery    400.0    RetailMart Kolkata East    Kolkata   East
6   Electronics   1500.0     RetailMart Mumbai West     Mumbai   West
7          Home    300.0  RetailMart Jaipur Central     Jaipur  North
8          Bags    700.0  RetailMart Bangalore Tech  Bangalore  South
9   Electronics  50000.0    RetailMart Kolkata East    Kolkata   East
10  Electronics    600.0       RetailMart Delhi Hub      Delhi  North
11  Electronics    500.0       RetailMart Pune City       Pune   West
12      Unknown      0.0  RetailMart Jaipur Central     Jaipur  North
13    Furniture    500.0  RetailMart Bangalore Tech  Bangalore  South
14   Stationery    400.0    RetailMart Kolkata East    Kolkata   East
15  Electronics   1500.0       RetailMart Delhi Hub      Delhi  North

    total_revenue
0        250000.0
1           900.0
2             0.0
3          1500.0
4          2000.0
5           800.0
6             0.0
7          1800.0
8          2100.0
9        100000.0
10          600.0
11         2500.0
12            0.0
13         2000.0
14         1200.0
15         3000.0

In [21]:
import sqlite3
conn = sqlite3.connect('retailmart.db')
final_df.to_sql(
    'retail_sales',
    conn,
    if_exists='replace',
    index=False
)

print("Data loaded successfully into retail_sales table.")
conn.close()

Data loaded successfully into retail_sales table.

In [22]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('retailmart.db')

query = """
SELECT
    product_id,
    product_name,
    SUM(quantity) AS total_quantity_sold
FROM retail_sales    
GROUP BY product_id, product_name
ORDER BY total_quantity_sold DESC
LIMIT 3;
"""

top_products = pd.read_sql(query, conn)
print(top_products)

conn.close()

  product_id  product_name  total_quantity_sold
0       P006   Study Table                  8.0
1       P001        Laptop                  7.0
2       P009  Water Bottle                  6.0

In [23]:
final_df.to_csv('retail_sales.csv', index=False)

In [24]:
import os
print(os.getcwd())

C:\Users\admin

In [25]:
print(final_df)

   sale_id store_id product_id  quantity  sale_date  amount    product_name  \
0     S001     ST01       P001       5.0 2026-06-01  2500.0          Laptop
1     S002     ST02       P003       2.0 2026-06-01   900.0        Keyboard
2     S003     ST03       P002       0.0 2026-06-01  1200.0  Wireless Mouse
3     S005     ST04       P005       1.0 2026-06-02  1500.0    Office Chair
4     S006     ST02       P006       4.0 2026-06-02  2000.0     Study Table
5     S007     ST05       P007       2.0 2026-06-03   800.0        Notebook
6     S008     ST03       P008       0.0 2026-06-03  3000.0         Printer
7     S009     ST01       P009       6.0 2026-06-03  1800.0    Water Bottle
8     S010     ST04       P010       3.0 2026-06-04  2100.0        Backpack
9     S011     ST05       P001       2.0 2026-06-04  1000.0          Laptop
10    S012     ST02       P002       1.0 2026-06-04   600.0  Wireless Mouse
11    S014     ST06       P004       5.0 2026-06-05  2500.0      Headphones
12    S015     ST01       P011       2.0 2026-06-05   999.0         Unknown
13    S016     ST04       P006       4.0        NaT  2000.0     Study Table
14    S017     ST05       P007       3.0 2026-06-06  1200.0        Notebook
15    S018     ST02       P008       2.0 2026-06-06  3000.0         Printer

       category    price                 store_name       city region  \
0   Electronics  50000.0  RetailMart Jaipur Central     Jaipur  North
1   Electronics    450.0       RetailMart Delhi Hub      Delhi  North
2   Electronics    600.0     RetailMart Mumbai West     Mumbai   West
3     Furniture   1500.0  RetailMart Bangalore Tech  Bangalore  South
4     Furniture    500.0       RetailMart Delhi Hub      Delhi  North
5    Stationery    400.0    RetailMart Kolkata East    Kolkata   East
6   Electronics   1500.0     RetailMart Mumbai West     Mumbai   West
7          Home    300.0  RetailMart Jaipur Central     Jaipur  North
8          Bags    700.0  RetailMart Bangalore Tech  Bangalore  South
9   Electronics  50000.0    RetailMart Kolkata East    Kolkata   East
10  Electronics    600.0       RetailMart Delhi Hub      Delhi  North
11  Electronics    500.0       RetailMart Pune City       Pune   West
12      Unknown      0.0  RetailMart Jaipur Central     Jaipur  North
13    Furniture    500.0  RetailMart Bangalore Tech  Bangalore  South
14   Stationery    400.0    RetailMart Kolkata East    Kolkata   East
15  Electronics   1500.0       RetailMart Delhi Hub      Delhi  North

    total_revenue
0        250000.0
1           900.0
2             0.0
3          1500.0
4          2000.0
5           800.0
6             0.0
7          1800.0
8          2100.0
9        100000.0
10          600.0
11         2500.0
12            0.0
13         2000.0
14         1200.0
15         3000.0

In [26]:
final_df.to_csv(r'C:\Users\admin\Downloads\retail_sales.csv',
                index=False)

In [27]:
total_transactions = len(final_df)

total_revenue = final_df['total_revenue'].sum()

top_city = final_df.groupby('city')['total_revenue'].sum().idxmax()

top_product = final_df.groupby('product_name')['quantity'].sum().idxmax() 


#Summary:
print("Summary Report")
print("Total Transactions:", total_transactions)
print("Total Revenue:", total_revenue)
print("Top Selling City:", top_city)
print("Top Selling Product:", top_product)

Summary Report
Total Transactions: 16
Total Revenue: 368400.0
Top Selling City: Jaipur
Top Selling Product: Study Table

In [32]:
import pandas as pd
import sqlite3

def run_pipeline():


 #Load:
    sales_df = pd.read_csv('sales_data.csv')
    products_df = pd.read_csv('products.csv')
    stores_df = pd.read_csv('stores.csv')

  # Remove duplicates:

    sales_df = sales_df.drop_duplicates()

  # missing values:

    sales_df['quantity'] = pd.to_numeric(
        sales_df['quantity'],
        errors='coerce'
    ).fillna(0)

    sales_df['amount'] = pd.to_numeric(
        sales_df['amount'],
        errors='coerce'
    )

    sales_df = sales_df.dropna(subset=['amount'])

   # datatype conversion:

    sales_df['sale_date'] = pd.to_datetime(
        sales_df['sale_date'],
        errors='coerce'
    )

    sales_df = sales_df.dropna(subset=['sale_date'])

    products_df['price'] = pd.to_numeric(
        products_df['price'],
        errors='coerce'
    ).fillna(0)

   # Merge DataFrames:

    final_df = sales_df.merge(
        products_df,
        on='product_id',
        how='left'
    ).merge(
        stores_df,
        on='store_id',
        how='left'
    )

   # Fill missing values:

    final_df['product_name'] = final_df['product_name'].fillna('Unknown')
    final_df['category'] = final_df['category'].fillna('Unknown')
    final_df['price'] = final_df['price'].fillna(0)

   # total_revenue:

    final_df['total_revenue'] = (
        final_df['quantity'] *
        final_df['price']
    )

   # Load into SQLite database:

    conn = sqlite3.connect('retailmart.db')

    final_df.to_sql(
        'retail_sales',
        conn,
        if_exists='replace',
        index=False
    )

    conn.close()

    print("Pipeline completed successfully!")
    print("Final Shape:", final_df.shape)

    return final_df

In [33]:
final_df = run_pipeline()

Pipeline completed successfully!
Final Shape: (15, 13)

In [34]:
import pandas as pd
import sqlite3

def run_pipeline():
    try:
        # Load CSV files:

        sales_df = pd.read_csv('sales_data.csv')
        products_df = pd.read_csv('products.csv')
        stores_df = pd.read_csv('stores.csv')

        # Clean data:

        sales_df = sales_df.drop_duplicates()
        sales_df['quantity'] = pd.to_numeric(
            sales_df['quantity'],
            errors='coerce'
        ).fillna(0)

        sales_df['amount'] = pd.to_numeric(
            sales_df['amount'],
            errors='coerce'
        )

        sales_df = sales_df.dropna(subset=['amount'])

        sales_df['sale_date'] = pd.to_datetime(
            sales_df['sale_date'],
            errors='coerce'
        )

        products_df['price'] = pd.to_numeric(
            products_df['price'],
            errors='coerce'
        ).fillna(0)

        # Merge DataFrames:

        final_df = sales_df.merge(
            products_df,
            on='product_id',
            how='left'
        ).merge(
            stores_df,
            on='store_id',
            how='left'
        )

        # Transform data:

        final_df['total_revenue'] = (
            final_df['quantity'] *
            final_df['price']
        )

        # Load into SQLite database:

        conn = sqlite3.connect('retailmart.db')

        final_df.to_sql(
            'retail_sales',
            conn,
            if_exists='replace',
            index=False
        )

        conn.close()

        print("Pipeline completed successfully!")
        return final_df

    except FileNotFoundError:
        print("Error: One or more CSV files are missing. Please check the file names and paths.")

In [35]:
final_df = run_pipeline()

Pipeline completed successfully!